### ISSUE TITLE
Bug in Static Property Node Accessor VI Creation

### ISSUE THREAD

**Issue by dnattinger** [opengds/OpenGDS#64]
(this bug originally posted here: https://forums.ni.com/t5/GDS-Goop-Development-Suite/Bug-in-Static-Property-Node-Accessor-VI-Creation/m-p/4142629 )

When you create a static dispatch property node accessor VI with regular non-GDS classes (i.e. using the native class editor features in LabVIEW), the new property VI is marked as Inline. The same does not happen when creating a static dispatch property node accessor VI with OpenGDS. It is created as a non-reentrant, non-inlined VI. From what I can tell this is because the property node accessor VI template is set to non-inlined to support being dynamic dispatch.  

To solve the issue for static dispatch property node accessor VIs, I propose a fix to the following VI:

_resource\Framework\Providers\Open_GDS\ClassProviders\Provider_LvNativeClass\ClassWriterNative_class\CreateMethod.vi_

I made the following edit to the VI, and now my static property node accessor VIs are marked as inline when they are created:

![gds_fix](https://user-images.githubusercontent.com/7662650/114802417-4af7a980-9d63-11eb-893b-f27c8055f432.png)

I assume a similar fix would need to be made to scripting for other class types (GOOP3, GOOP4, etc.), but I didn't dig into their scripting code so I wasn't sure.

**Comment by MikaelHolmstrom** [comment]
Done, in the 2020 branch.
Planning of building a new version next week

**Comment by MichaelAivaliotis** [comment]
It seems that this bug is still active in the latest LV2020 branch v1.2.72. I checked the code and it seems to be as shown in the image, so i'm not sure what the problem is. I can reproduce it using the LVClass by value and the GOOP4 class provider.

**Comment by MikaelHolmstrom** [comment]
It is there i the code, if it's a Property Node Method and Not Dynamic Dispatch, it should set it to that?!?

**Comment by MikaelHolmstrom** [comment]
Found it, you can get an error if you do this in parallel, since the dynamic dispatch setting is still being turned off.
V1.2.74 is coming tomorrow
